name: CI/CD Pipeline
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: my-runner
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: file system scanning
        run: trivy fs --format table -o trivy-fs-report.html .
      - name: docker img build & tag
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ollama-task:latest .
      - name: docker image scanning
        run: trivy image --format table -o trivy-img-report.html ${{ secrets.DOCKERHUB_USERNAME }}/ollama-task:latest
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: docker image push 
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ollama-task:latest

