name: CI/CD Pipeline
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: my-runner
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: file system scanning
        run: trivy fs --format table -o trivy-fs-report.html .
      - name: docker img build & tag
        run: docker build -t mukeshr29/ollama-task:latest .
      - name: docker image scanning
        run: trivy image --format table -o trivy-img-report.html mukeshr29/ollama-task:latest
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: docker image push 
        run: docker push mukeshr29/ollama-task:latest
      
  deploy:
    name: deploy to k8s
    needs: build
    runs-on: my-runner
    steps:
      - name: deploy application to kubeAdm
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - run: |
          kubectl apply -f deployment.yaml -n devops-assignment
          kubectl apply -f service.yaml -n devops-assignment
          kubectl apply -f hpa.yaml -n devops-assignment


